### ISSUE TITLE
Header extraction failure

### ISSUE THREAD

**Issue by io7m** [io7m/idstore#99]
```
Dec 17 11:13:02 services02 podman[78986]: idstore: com.io7m.idstore.server.http.IdHTTPHandlerFunctional: DEBUG: Uncaught exception:
Dec 17 11:13:02 services02 podman[78986]: java.util.NoSuchElementException: Header HeaderNameImpl[lowerCase=traceparent, defaultCase=traceparent] is not present in these headers
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.http@4.0.1/io.helidon.http.HeadersImpl.get(HeadersImpl.java:81)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.http@4.0.1/io.helidon.http.ServerRequestHeadersImpl.get(ServerRequestHeadersImpl.java:55)
Dec 17 11:13:02 services02 podman[78986]:         at com.io7m.idstore.server.http@1.0.0-rc0002/com.io7m.idstore.server.http.IdHTTPServerRequestContextExtractor.get(IdHTTPServerRequestContextExtractor.java:73)
Dec 17 11:13:02 services02 podman[78986]:         at com.io7m.idstore.server.http@1.0.0-rc0002/com.io7m.idstore.server.http.IdHTTPServerRequestContextExtractor.get(IdHTTPServerRequestContextExtractor.java:30)
Dec 17 11:13:02 services02 podman[78986]:         at io.opentelemetry.api@1.33.0/io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator.extractImpl(W3CTraceContextPropagator.java:150)
Dec 17 11:13:02 services02 podman[78986]:         at io.opentelemetry.api@1.33.0/io.opentelemetry.api.trace.propagation.W3CTraceContextPropagator.extract(W3CTraceContextPropagator.java:141)
Dec 17 11:13:02 services02 podman[78986]:         at com.io7m.idstore.server.http@1.0.0-rc0002/com.io7m.idstore.server.http.IdHTTPHandlerCoreInstrumented.execute(IdHTTPHandlerCoreInstrumented.java:89)
Dec 17 11:13:02 services02 podman[78986]:         at com.io7m.idstore.server.http@1.0.0-rc0002/com.io7m.idstore.server.http.IdHTTPHandlerFunctional.handle(IdHTTPHandlerFunctional.java:76)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.webserver@4.0.1/io.helidon.webserver.http.HttpRouting$RoutingExecutor.doRoute(HttpRouting.java:668)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.webserver@4.0.1/io.helidon.webserver.http.HttpRouting$RoutingExecutor.call(HttpRouting.java:627)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.webserver@4.0.1/io.helidon.webserver.http.HttpRouting$RoutingExecutor.call(HttpRouting.java:605)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.webserver@4.0.1/io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
Dec 17 11:13:02 services02 podman[78986]:         at io.helidon.webserver@4.0.1/io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:121)
Dec 17 11:13:02 services02 podman[78986]:         at com.io7m.idstore.server.http@1.0.0-rc0002/com.io7m.idstore.server.http.IdHTTPRequestTimeFilter.filter(IdHTTPRequestTimeFilter.java:75)
```

**Comment by io7m** [comment]
This happens when telemetry is enabled but no trace context is present.
